name = "KrakenEx"
uuid = "905906f8-4650-4186-8b30-13842c9f1f1c"
authors = ["Benjamin Thomas Schwertfeger"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
